apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-spring-boot-docker
  template:
    metadata:
      labels:
        app: demo-spring-boot-docker
    spec:
      containers:
        - name: demo-spring-boot-docker
          image: dfjmax/demo-spring-boot-docker
          ports:
            - containerPort: 8080
              name: http
---

apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-docker
spec:
  selector:
    app: demo-spring-boot-docker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer