spring:
  application:
    name: demo-spring-boot-docker
  datasource:
      url: jdbc:postgresql://localhost:5432/demo?reWriteBatchedInserts=true
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.generate_statistics: false
      hibernate.show_sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
server:
  port: 8080